
services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
    command: supervisor -e  'js,pug,html' index.js
    ports:
      - "3000:3000"
      - "8443:443"  # Map HTTPS port to 8443 to avoid permission issues
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HTTPS_PORT=443
      - USE_HTTPS=true
      - SESSION_SECRET=scholars_united_secret_key
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=StudyBuddies
    ports:
      - "3309:3306"
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    env_file:
      - ./.env
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "8082:80"
