name: Basic Docker Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  verify:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install
    
    - name: Start Docker services
      run: docker-compose up -d db  # Start only MySQL first
    
    - name: Verify server starts with Docker
      run: |
        docker-compose build web  # Build the web service
        docker-compose up -d web  # Start the web service
        sleep 10  # Wait for both MySQL and Express to initialize
        docker-compose ps  # Show running services (debugging)
        curl -s http://localhost:3000 || exit 0
