# This is a basic workflow that is triggered by a push to the develop branch

name: On push to develop branch

# Controls when the action will run. Triggered by push to develop branch
on:
  push:
    branches:
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send message
      run: echo "The develop branch has been updated"
